# -*- mode: yaml-*-
# vi: set ft=yaml sw=2 ts=2 :

- name: Work machine
  hosts: all
  sudo: True
  tasks:
    - name: set locale
      lineinfile: dest=/etc/default/locale line="LC_ALL=C"

    - name: install packages
      apt: name={{ item }} update_cache=yes
      with_items:
        - git
        - curl

    - name: add ppa with node
      shell: curl -sL https://deb.nodesource.com/setup | bash -

    - name: install node and npm
      apt: name=nodejs update_cache=yes

    - name: install node dependencies
      npm: path=/opt/project

    - name: change working directory
      lineinfile: dest=/home/vagrant/.bashrc line='cd /opt/project'

    - name: Add mongo ppa key
      apt_key: >
        keyserver=hkp://keyserver.ubuntu.com:80
        id=7F0CEB10
        state=present

    - name: Add mongo sources list
      lineinfile: >
        line="deb http://repo.mongodb.org/apt/ubuntu {{ansible_lsb.codename}}/mongodb-org/3.0 multiverse"
        dest=/etc/apt/sources.list.d/mongodb.list
        state=present
        create=yes

    - name: Install mongo
      apt: name=mongodb-org state=latest update_cache=yes
